# DOCKER COMPOSE CONFIGURATION
# docker-compose.yml
services:
  user-interface:
    build: ./user-interface
    ports:
      - "5000:5000"
    depends_on:
      - trip-management
      - itinerary
      - recommendation-management
      - rabbitmq
      - finance

  trip-management:
    build: ./trip-management
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  itinerary:
    build: ./itinerary
    ports:
      - "5002:5002"
    depends_on:
      - trip-management

  recommendation-management:
    build: ./recommendation-management
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"